### PR TITLE
Open Link Settings

### PR DESCRIPTION
**Pull request by kernjackson**
## Overview

Adds Reader View and 3rd party browser support.

- [x] Add setting to open links in Reader View #581 
- [x] Add setting to open links in 3rd party browsers #598 

`OpenLinker` is adapted from the [Proton Mail for iOS](https://github.com/ProtonMail/ios-mail), which is covered under the [GPL-3.0 license](https://github.com/TheBLVD/mammoth/compare/main...kernjackson:mammoth:open-link-settings?expand=1#GPL-3.0-1-ov-file).

Settings View
Users can quickly toggle Reader View on or off in settings.

Browser Selection
Users can select a default 3rd party browser to open links with.

## Testing

I was able to test this in the simulator with the following

- [x] Safari
- [x] Mammoth
- [x] Reader View
- [ ] Brave
- [ ] Chrome
- [x] DuckDuckGo
- [ ] Edge
- [ ] Firefox
- [ ] Firefox Focus
- [ ] Opera Mini
- [ ] Opera Touch

### CODE REVIEW

**Comment by bnolens** [comment]
Very cool!
You probably want to add Safari in the list too?

**Comment by rileyhCode** [comment]
The user can change their default browser from Safari to something else. If they do that, is there a way for them to specify Safari here?

**Comment by rileyhCode** [comment]
One additional note: would need to add Proton Mail to the list of licenses/attributions in About.

**Comment by kernjackson** [comment]
Good point @rileyhCode, I will add that.

**Review by derspyy — APPROVED** [review]

**Comment by derspyy** [comment]
@kernjackson do you think you get sign your commits? i'm pretty sure you can sign them retroactively but feel free to make a new PR.

(p.s. the change i made to localizable is just in order to fix some conflicts, don't mind that, but also you don't need to include that file again because i'll add all new strings later)

**Pull request merged**
