### PR TITLE
MAM-4048-double-tap-home-is-unreliable

### PR DESCRIPTION
**Pull request by bnolens**
https://linear.app/theblvd/issue/MAM-4048/double-tap-home-is-unreliable

Improved like-count reliability
Increased touch area for like-button

### CODE REVIEW

**Comment by derspyy** [comment]
oh, looks like the logic was simplified a bit. always good to hear that, lgtm.

**Comment by derspyy** [comment]
though is this the right ticket?

**Comment by bnolens** [comment]
> though is this the right ticket?

Aw, wrong ticket. Changing this now

**Comment by bnolens** [comment]
renamed into https://github.com/TheBLVD/mammoth/pull/505

**Comment by derspyy** [comment]
haha no worries

**Pull request closed without merging**
